<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [X2Go-Dev] Bug#18: Issue hopefully fixed in python-x2go 0.4.0.0
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/x2go-dev/2013-February/index.html" >
   <LINK REL="made" HREF="mailto:x2go-dev%40lists.berlios.de?Subject=Re%3A%20%5BX2Go-Dev%5D%20Bug%2318%3A%20Issue%20hopefully%20fixed%20in%20python-x2go%200.4.0.0&In-Reply-To=%3C1360625561.2219.5.camel%40Nokia-N900%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="004991.html">
   <LINK REL="Next"  HREF="004993.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[X2Go-Dev] Bug#18: Issue hopefully fixed in python-x2go 0.4.0.0</H1>
    <B>Mike Gabriel</B> 
    <A HREF="mailto:x2go-dev%40lists.berlios.de?Subject=Re%3A%20%5BX2Go-Dev%5D%20Bug%2318%3A%20Issue%20hopefully%20fixed%20in%20python-x2go%200.4.0.0&In-Reply-To=%3C1360625561.2219.5.camel%40Nokia-N900%3E"
       TITLE="[X2Go-Dev] Bug#18: Issue hopefully fixed in python-x2go 0.4.0.0">mike.gabriel at das-netzwerkteam.de
       </A><BR>
    <I>Tue Feb 12 00:32:41 CET 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="004991.html">[X2Go-Dev] Processed: Re: Bug#105: Logic errors in x2goruncommand
</A></li>
        <LI>Next message: <A HREF="004993.html">[X2Go-Dev] Processed: Issue hopefully fixed in python-x2go 0.4.0.0
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4992">[ date ]</a>
              <a href="thread.html#4992">[ thread ]</a>
              <a href="subject.html#4992">[ subject ]</a>
              <a href="author.html#4992">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>tag #18 pending
thanks

The issue described by [1] is hopefully fixed in python-x2go 0.4.0.0 (in prep) after several modifications to the SSH proxy code.

The observed error has not been seen for a while now...

Marking this issue is pending for upload...

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, rothenstein 5, 24214 neudorf-bornstein
fon: +49 (1520) 1976148

GnuPG Key ID 0x25771B13
mail: <A HREF="https://lists.berlios.de/mailman/listinfo/x2go-dev">mike.gabriel at das-netzwerkteam.de</A>, <A HREF="http://das-netzwerkteam.de">http://das-netzwerkteam.de</A>
</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="004991.html">[X2Go-Dev] Processed: Re: Bug#105: Logic errors in x2goruncommand
</A></li>
	<LI>Next message: <A HREF="004993.html">[X2Go-Dev] Processed: Issue hopefully fixed in python-x2go 0.4.0.0
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4992">[ date ]</a>
              <a href="thread.html#4992">[ thread ]</a>
              <a href="subject.html#4992">[ subject ]</a>
              <a href="author.html#4992">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/x2go-dev">More information about the X2Go-Dev
mailing list</a><br>
</body></html>
