<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [X2Go-Dev] Processed: your mail
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/x2go-dev/2013-March/index.html" >
   <LINK REL="made" HREF="mailto:x2go-dev%40lists.berlios.de?Subject=Re%3A%20%5BX2Go-Dev%5D%20Processed%3A%20your%20mail&In-Reply-To=%3Chandler.s.C.136213301011905.transcript%40bugs.x2go.org%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="005228.html">
   <LINK REL="Next"  HREF="005130.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[X2Go-Dev] Processed: your mail</H1>
    <B>X2Go Bug Tracking System</B> 
    <A HREF="mailto:x2go-dev%40lists.berlios.de?Subject=Re%3A%20%5BX2Go-Dev%5D%20Processed%3A%20your%20mail&In-Reply-To=%3Chandler.s.C.136213301011905.transcript%40bugs.x2go.org%3E"
       TITLE="[X2Go-Dev] Processed: your mail">git-admin at x2go.org
       </A><BR>
    <I>Fri Mar  1 11:18:03 CET 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="005228.html">[X2Go-Dev] Bug#129: X Error: BadAccess (attempt to access private	resource denied) 10 - Extension: 129 (MIT-SHM)
</A></li>
        <LI>Next message: <A HREF="005130.html">[X2Go-Dev] Bug#130: Update of sessions from pyhoca-gui does not work
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#5128">[ date ]</a>
              <a href="thread.html#5128">[ thread ]</a>
              <a href="subject.html#5128">[ subject ]</a>
              <a href="author.html#5128">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Processing commands for <A HREF="https://lists.berlios.de/mailman/listinfo/x2go-dev">control at bugs.x2go.org</A>:

&gt;<i> tag #127 - moreinfo
</I>Bug #127 [x2gobroker-daemon] x2gobroker-daemon deb package reinstall/upgrade fails
Removed tag(s) moreinfo.
&gt;<i> thanks
</I>Stopping processing here.

Please contact me if you need assistance.
-- 
127: <A HREF="http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=127">http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=127</A>
X2Go Bug Tracking System
Contact <A HREF="https://lists.berlios.de/mailman/listinfo/x2go-dev">git-admin at x2go.org</A> with problems
</PRE>






<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="005228.html">[X2Go-Dev] Bug#129: X Error: BadAccess (attempt to access private	resource denied) 10 - Extension: 129 (MIT-SHM)
</A></li>
	<LI>Next message: <A HREF="005130.html">[X2Go-Dev] Bug#130: Update of sessions from pyhoca-gui does not work
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#5128">[ date ]</a>
              <a href="thread.html#5128">[ thread ]</a>
              <a href="subject.html#5128">[ subject ]</a>
              <a href="author.html#5128">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/x2go-dev">More information about the X2Go-Dev
mailing list</a><br>
</body></html>
